<?php

function sartori_init(){

	//Javascript's load
	// drupal_add_js(base_path()."sites/all/modules/sartori/js/jquery.validate.min.js");
	// drupal_add_js(base_path()."sites/all/modules/sartori/js/jquery.maskedinput.min.js");
	// drupal_add_js(base_path()."sites/all/modules/sartori/js/general.js");

}

/**
 * Implements hook_form_alter.
 */
function sartori_form_alter(&$form, &$form_state, $form_id) {

	// Fill the title of the node on the validation.
	if ($form_id == "contato_node_form"){
    $form['title']['#required'] = FALSE;
    $form['#validate'][] = 'sartori_contato_validate';
  }

  if ($form_id == "andamento_processual_node_form"){
    if (isset($_GET['proc'])) {
      $processo = $_GET['proc'];
      $form['field_processo'][LANGUAGE_NONE]['#default_value'] = $processo;
      $form['field_processo']['#disabled'] = TRUE;
    }

    $form['#validate'][] = 'sartori_acompanhamento_validate';
	}

	if ($form_id == "dados_da_pasta_node_form") {
    // Edit form
    if ($form['#node_edit_form']) {
      $form['field_n_inicial']['#disabled'] = TRUE;
    }

		// Add node form
		if (!isset($form['nid']['#value'])) {
			global $user;
      $form['#validate'][] = 'sartori_processo_validate';
			$form['field_advogado_responsavel'][LANGUAGE_NONE]['#default_value'] = array($user->uid);
			$form['title']['#default_value'] = sartori_generate_next_pasta_id();
		}
	}
}

/**
 * Implements hook_form_validate.
 */
function sartori_contato_validate(&$form, &$form_state) {
  if ($form_state['values']['field_tipo_de_pessoa'][LANGUAGE_NONE][0]['value'] == 'fisica') {
    $form_state['values']['title'] = $form_state['values']['field_nome'][LANGUAGE_NONE][0]['value'];
  }
  else {
    $form_state['values']['title'] = $form_state['values']['field_razao_social'][LANGUAGE_NONE][0]['value'];
  }
}

/**
 * Implements hook_form_submit.
 */
function sartori_processo_validate(&$form, &$form_state) {
  $form_state['values']['field_n_principal'][LANGUAGE_NONE][0]['value'] = $form_state['values']['field_n_inicial'][LANGUAGE_NONE][0]['value'];
}

/**
 * Function to generate the next id for pasta.
 * @return string
 */
function sartori_generate_next_pasta_id() {
	$last_id = db_select('node', 'n')
    ->fields('n', array('title'))
    ->condition('type', 'dados_da_pasta')
    ->orderBy('title', 'DESC')
    ->range(0,1)
    ->execute()
    ->fetchAssoc();
  $id_number = str_replace('Proc-', '', $last_id['title']);
  $id_number += 1;
  $remaining_chars = 7 - drupal_strlen($id_number);
  $next_id = 'Proc-' . str_repeat('0', $remaining_chars) . $id_number;
  return $next_id;
}
